apiVersion: v1
kind: Pod
metadata:
  name: refinemetrics-exporter
  namespace: kubeiaas
spec:
  nodeSelector:
    kubernetes.io/hostname: hf-node-02
  imagePullSecrets:
  - name: regsecret-wzq
  containers:
  - name: refinemetrics-exporter
    image: registry.cn-beijing.aliyuncs.com/hufu-dev/refinemetrics-exporter:dev-latest
    imagePullPolicy: Always
    args: ["--web.disable-exporter-metrics"]
    ports:
    - containerPort: 9188
      hostPort: 9188