prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'refineMetrics-exporter'
        scrape_interval: 5m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        static_configs:
        - targets:
          - 192.168.33.7:9188